### ISSUE TITLE
Larger Hex size wanted

### ISSUE THREAD

**Issue by DavidTweito** [AlexanderSharykin/HexGrid#3]
First, thank you for making your project available. I appreciate you taking the time to do that.

Secondly, I need to have a 25 x 25 hex list with horizontal orientation.   I have spent significant time with the code to figure out how I might create much larger hexagons, but with no luck.   I'm not great at WPF and I'm still learning, so any suggestions you could offer would be helpful.

![image](https://user-images.githubusercontent.com/60157383/72843021-b2f63780-3c67-11ea-9690-3650071c6cca.png)

The image shows what I am getting, which is far too compacted for me.

Thank you,

David.

**Comment by AlexanderSharykin** [comment]
Add a Setter in HexItem style here:
https://github.com/AlexanderSharykin/HexGrid/blob/master/HexGridDemo/SamplesWindow.xaml#L62
< Setter Property="MinHeight" Value="55" />
or Setter for Height to get fixed size

Alternatively increase size of content in ItemTemplate here:
https://github.com/AlexanderSharykin/HexGrid/blob/master/HexGridDemo/SamplesWindow.xaml#L66
< TextBlock Height="45" >
